### TESTE DA RAIZ DA API
GET http://localhost:5290

########### PLANO

### Cadastrar plano
POST http://localhost:5290/api/plano/cadastrar
Content-Type: application/json

{
    "nome" : "Plano Livre",
    "descricao" : "Sem personal trainer, nutricionista ou treino personalizado.",
    "preco" : 99.90
}

### Listar Planos
GET http://localhost:5290/api/plano/listar

### Buscar Plano
GET http://localhost:5290/api/plano/buscar/12

### Alterar Plano
PUT http://localhost:5290/api/plano/alterar/12
Content-Type: application/json

{
    "nome" : "Plano VIP",
    "descricao" : "Acesso ao treino personalizado, mas sem personal trainer ou nutricionista",
    "preco" : 149.90
}

### Deletar Plano
DELETE http://localhost:5290/api/plano/deletar/10

########### ALUNO

### Cadastrar Aluno
POST http://localhost:5290/api/aluno/cadastrar
Content-Type: application/json

{
    "nome" : "Igor Viana",
    "email" : "Igor@email.com",
    "planoId" : 12
}

### Listar Alunos
GET http://localhost:5290/api/aluno/listar

### Deletar Aluno pelo ID
DELETE http://localhost:5290/api/aluno/deletar/5


### Buscar Aluno pelo ID
GET http://localhost:5290/api/aluno/buscar/5

### Alterar Aluno pelo ID
PUT http://localhost:5290/api/aluno/alterar/5
Content-Type: application/json

{
    "nome": "Nicolas Yasumoto",
    "email": "nicolas@email.com",
    "planoId": 12
}
